version: build-{build}
image: Visual Studio 2017
configuration: Release
platform:
  - Win32
  - x64
install:
  - choco upgrade git -y
  - if %platform%==Win32 set VCPKG_TRIPLET=x86-windows
  - if %platform%==x64 set VCPKG_TRIPLET=x64-windows
  - vcpkg install libogg:%VCPKG_TRIPLET% libvorbis:%VCPKG_TRIPLET% libflac:%VCPKG_TRIPLET%
before_build:
  - mkdir CMakeBuild
  - cd CMakeBuild
  - if %platform%==Win32 set CMAKE_GENERATOR=Visual Studio 15 2017
  - if %platform%==x64 set CMAKE_GENERATOR=Visual Studio 15 2017 Win64
  - cmake -G"%CMAKE_GENERATOR%" -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_BUILD_TYPE="Release" -DBUILD_TESTING=ON ..
build_script:
  - cmake --build . --config Release
test_script:
  - ctest -V -C "Release"
cache:
  # last updated: 2018-03-02
  C:\Tools\vcpkg\Installed -> appveyor.yml

