dist: travis_latest
group: edge
sudo: false
language: c

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          packages:
            - libogg-dev
            - libvorbis-dev
            - libflac-dev
            - libasound2-dev
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages:
            - libogg-dev
            - libvorbis-dev
            - libflac-dev
            - libasound2-dev
    - os: osx
      compiler: clang
before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install flac libogg libvorbis
    fi

install:
  - true

script:
  - mkdir cmake-build && (cd cmake-build && cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=ON && make VERBOSE=1 && ctest -V)
